name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      id: go
      with:
        go-version: '>=1.22.0'
    - name: Test
      run: go test -v .
      env:
        CGO_ENABLED: 0
